services:
  codex-dist-test:
    image: codexstorage/nim-codex:stable-dist-tests
    pull_policy: always
    container_name: codex
    command:
      - codex
      - persistence
      - prover
    environment:
      - NETWORK=testnet
      - CODEX_DATA_DIR=/data
      - CODEX_CIRCUIT_DIR=/circuit
      - CODEX_API_PORT=8080
      - CODEX_API_BINDADDR=0.0.0.0
      - CODEX_API_CORS_ORIGIN="*"
      - CODEX_LISTEN_ADDRS=/ip4/0.0.0.0/tcp/8070
      - CODEX_DISC_PORT=8090
      - NAT_PUBLIC_IP_AUTO=https://ip.codex.storage
      - CODEX_ETH_PROVIDER=https://rpc.testnet.codex.storage
      - CODEX_VALIDATOR=false
      # Update or export a variable with a private key value
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY:-<<< PRIVATE KEY HERE >>>}
    ports:
      - 8081:8081/tcp # API
      - 8070:8070/tcp # Transport
      - 8090:8090/udp # Discovery
    volumes:
      - ./codex-data:/data
      - ./codex-circuit:/circuit
    network_mode: host
